version: '4'
services:
  postgres:
    image: postgres:15
    container_name: users
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres101
      POSTGRES_DB: db_order
      PGDATA: /var/lib/postgresql/data

    ports:
      - "5450:5450"
